/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103x8.h"
#include "GPIO.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




void Clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}


void GPIO_init()
{
	//PA1 floating input (by default)
	GPIO_PinConfig_t PA1;
	PA1.GPIO_PinNumber = GPIO_PIN_1;
	PA1.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PA1);

	//PA13 floating input (by default)
	GPIO_PinConfig_t PA13;
	PA13.GPIO_PinNumber = GPIO_PIN_13;
	PA13.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PA13);



	GPIO_PinConfig_t PB1;
	PB1.GPIO_PinNumber = GPIO_PIN_1;
	//PB1 output mode at 10 mhz
	PB1.GPIO_Output_Speed = GPIO_SPEED_10M;
	//PB1 push pull output
	PB1.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	MCAL_GPIO_Init(GPIOB, &PB1);


	GPIO_PinConfig_t PB13;
	PB13.GPIO_PinNumber = GPIO_PIN_13;
	//PB13 output mode at 10 mhz
	PB13.GPIO_Output_Speed = GPIO_SPEED_10M;
	//PB13 push pull output
	PB13.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	MCAL_GPIO_Init(GPIOB, &PB13);





}



int main(void)
{
	Clock_init();
	GPIO_init();

	while(1)
    {
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0){
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1){
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		volatile int i ;
		for(i = 0; i<10000; i++);
    }

}

